name: Deploy Blazor App to GitHub Pages

on:
  push:
    branches:
      - main  # Set this to your default branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '6.0'  # Set this to the .NET version you are using

      - name: Restore dependencies
        run: dotnet restore

      - name: Build and Publish
        run: dotnet publish -c Release -o ./build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build/wwwroot  # Adjust the path according to your publish directory
